version: '3'
services:
  skinwarriors-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3001:3000'
    volumes:
      - .:/app

  skinwarriors-api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    command: npm start
